get_saved_state_r1 – ISOFT
get_saved_state_r1 Function
30 statements
Source File
private function get_saved_state_r1(srname, save_states)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: srname
integer, intent(inout), dimension(7) :: save_states
Return Value integer
Called by
Contents
Source Code
get_saved_state_r1
Source Code
function get_saved_state_r1(srname,save_states)
!
! Part of rksuite_90 v1.0 (Aug 1994)
!         software for initial value problems in ODEs
!
! Authors: R.W. Brankin (NAG Ltd., Oxford, England)
!          I. Gladwell  (Math Dept., SMU, Dallas, TX, USA)
!          see main doc for contact details
!
integer, dimension(7), intent(inout) :: save_states
character(len=*), intent(in) :: srname
integer :: get_saved_state_r1
!
integer :: name
!
integer, parameter :: fatal=911
!
select case (srname)
   case("SETUP"); name = 1
   case("RANGE_INTEGRATE"); name = 2
   case("STATISTICS"); name = 3
   case("GLOBAL_ERROR"); name = 4
   case("STEP_INTEGRATE"); name = 5
   case("INTERPOLATE"); name= 6
   case("RESET_T_END"); name = 7
   case default; name = 0
end select
!
!  Check for status of given routine but check for any fatal errors first
!
if (any(save_states(1:7)==fatal)) then
   get_saved_state_r1 = fatal
else
   get_saved_state_r1 = save_states(name)
end if
!
end function get_saved_state_r1
Call graph
step_integrate_r1 calls get_saved_state_r1
interpolate_r1 calls get_saved_state_r1
global_error_r1 calls get_saved_state_r1
reset_t_end_r1 calls get_saved_state_r1
range_integrate_r1 calls get_saved_state_r1, reset_t_end, interpolate, step_integrate
statistics_r1 calls get_saved_state_r1
reset_t_end calls reset_t_end_r1
interpolate calls interpolate_r1
step_integrate calls step_integrate_r1
range_integrate calls range_integrate_r1
global_error calls global_error_r1
statistics calls statistics_r1
upstream_calculate calls range_integrate