machine_const – ISOFT
machine_const Subroutine
11 statements
Source File
private subroutine machine_const(round_off, sqrrmc, cubrmc, sqtiny, outch)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out) :: round_off
real(kind=wp), intent(out) :: sqrrmc
real(kind=wp), intent(out) :: cubrmc
real(kind=wp), intent(out) :: sqtiny
integer, intent(out) :: outch
Called by
Contents
Source Code
machine_const
Source Code
subroutine machine_const(round_off,sqrrmc,cubrmc,sqtiny,outch)
!
! Part of rksuite_90 v1.0 (Aug 1994)
!         software for initial value problems in ODEs
!
! Authors: R.W. Brankin (NAG Ltd., Oxford, England)
!          I. Gladwell  (Math Dept., SMU, Dallas, TX, USA)
!          see main doc for contact details
!
real(kind=wp), intent(out) :: round_off, sqrrmc, cubrmc, sqtiny
integer, intent(out) :: outch
!
real(kind=wp) :: dummy
real(kind=wp), parameter :: third=1.0_wp/3.0_wp, ten=10.0_wp
!
outch = 6
!
round_off = ten*epsilon(dummy)
sqrrmc = sqrt(epsilon(dummy))
cubrmc = epsilon(dummy)**third
sqtiny = sqrt(tiny(dummy))
!
end subroutine machine_const
Call graph
setup_r1 calls machine_const
setup calls setup_r1
upstream_calculate calls setup