set_saved_state_r1 – ISOFT
set_saved_state_r1 Subroutine
27 statements
Source File
private subroutine set_saved_state_r1(srname, state, comm)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: srname
integer, intent(in) :: state
type(rk_comm_real_1d), intent(inout) :: comm
Called by
Contents
Source Code
set_saved_state_r1
Source Code
subroutine set_saved_state_r1(srname,state,comm)
!
! Part of rksuite_90 v1.0 (Aug 1994)
!         software for initial value problems in ODEs
!
! Authors: R.W. Brankin (NAG Ltd., Oxford, England)
!          I. Gladwell  (Math Dept., SMU, Dallas, TX, USA)
!          see main doc for contact details
!
integer, intent(in) :: state
type(rk_comm_real_1d), intent(inout) :: comm
character(len=*), intent(in) :: srname
!
integer :: name
!
integer, parameter :: fatal=911
!
select case (srname)
   case("SETUP"); name = 1
   case("RANGE_INTEGRATE"); name = 2
   case("STATISTICS"); name = 3
   case("GLOBAL_ERROR"); name = 4
   case("STEP_INTEGRATE"); name = 5
   case("INTERPOLATE"); name= 6
   case("RESET_T_END"); name = 7
   case default; name = 0
end select
!
comm%save_states(name) = state
comm%saved_fatal_err = state >= fatal
!
end subroutine set_saved_state_r1
Call graph
rkmsg_r1 calls set_saved_state_r1
step_integrate_r1 calls set_saved_state_r1, rkmsg_r1
range_integrate_r1 calls set_saved_state_r1, rkmsg_r1, step_integrate, reset_t_end, interpolate
interpolate_r1 calls rkmsg_r1
step_integrate calls step_integrate_r1
range_integrate calls range_integrate_r1
setup_r1 calls rkmsg_r1
reset_t_end_r1 calls rkmsg_r1
global_error_r1 calls rkmsg_r1
statistics_r1 calls rkmsg_r1
reset_t_end calls reset_t_end_r1
upstream_calculate calls range_integrate, setup
interpolate calls interpolate_r1
global_error calls global_error_r1
statistics calls statistics_r1
setup calls setup_r1