version – ISOFT
version Module Function
3 statements
Source File
module function version() Interface →
Arguments
None
Return Value real
Called by
Contents
Source Code
version
Source Code
  module function version()
    version = version_num
  end function version
Call graph
version calls version
read_ice calls version
write_data calls version
read_sub_ice calls version
read_data calls version