coriolis_block – ISOFT
coriolis_block Interface
3 statements
Source File
public interface coriolis_block
Calls
Contents
Module Procedures
constructor
Module Procedures
private function constructor(phi, nu, velbound, dvelbound, integrate_bound, template) result(this)
Author
Chris MacMackin
Date
January 2018
Builds a Coriolis block which can be used to solve the inverse problem for the linear components of the plume momentum equations. The result can only be used with fields having the same grid as the template.
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(in) :: phi
The dimensionless coriolis parameter
real(kind=r8), intent(in) :: nu
The dimensionless eddy diffusivity
integer, intent(in) :: velbound
Location code for the velocity's boundary condition. 1 indicates upper boundary, -1 indicates lower boundary.
integer, intent(in) :: dvelbound
Location code for the velocity's boundary condition. 1 indicates upper boundary, -1 indicates lower boundary.
integer, intent(in) :: integrate_bound
Location code for the boundary to perform integrations from. This should be the opposite boundary from where boundary data is stored.
class(abstract_field), intent(in) :: template
A scalar field with the same grid as any fields passed as arguments to the solve_for method.
Return Value type(coriolis_block)
Call graph
coriolis_block calls constructor
constructor calls uniform_scalar_field, la_gesvx, vinv_r, vinv_i, str, cheb1d_scalar_field, emdx_i, emdx_r