range_integrate – ISOFT
range_integrate Interface
3 statements
Source File
public interface range_integrate
Calls
Called by
Contents
Module Procedures
range_integrate_r1
Module Procedures
private recursive subroutine range_integrate_r1(comm, f, t_want, t_got, y_got, yderiv_got, flag)
Arguments
Type Intent Optional Attributes Name
type(rk_comm_real_1d), intent(inout) :: comm
public function f(t, y)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in), dimension(:) :: y
Return Value real(kind=wp), dimension(size(y,1))
real(kind=wp), intent(in) :: t_want
real(kind=wp), intent(out) :: t_got
real(kind=wp), intent(out), dimension(:) :: y_got
real(kind=wp), intent(out), dimension(:) :: yderiv_got
integer, intent(out), optional :: flag
Call graph
range_integrate calls range_integrate_r1
range_integrate_r1 calls reset_t_end, interpolate, step_integrate, set_saved_state_r1, get_saved_state_r1, rkmsg_r1, get_saved_fatal_r1
reset_t_end calls reset_t_end_r1
interpolate calls interpolate_r1
step_integrate calls step_integrate_r1
rkmsg_r1 calls set_saved_state_r1, get_stop_on_fatal_r1
step_integrate_r1 calls set_saved_state_r1, get_saved_state_r1, rkmsg_r1, stiff_r1, step_r1, truerr_r1
interpolate_r1 calls get_saved_state_r1, rkmsg_r1
reset_t_end_r1 calls get_saved_state_r1, rkmsg_r1
truerr_r1 calls step_r1
upstream_calculate calls range_integrate