setup – ISOFT
setup Interface
3 statements
Source File
public interface setup
Calls
Called by
Contents
Module Procedures
setup_r1
Module Procedures
private subroutine setup_r1(comm, t_start, y_start, t_end, tolerance, thresholds, method, task, error_assess, h_start, message)
Arguments
Type Intent Optional Attributes Name
type(rk_comm_real_1d) :: comm
real(kind=wp), intent(in) :: t_start
real(kind=wp), intent(in), dimension(:) :: y_start
real(kind=wp), intent(in) :: t_end
real(kind=wp), intent(in) :: tolerance
real(kind=wp), intent(in), dimension(:) :: thresholds
character(len=*), intent(in), optional :: method
character(len=*), intent(in), optional :: task
logical, intent(in), optional :: error_assess
real(kind=wp), intent(in), optional :: h_start
logical, intent(in), optional :: message
Call graph
setup calls setup_r1
setup_r1 calls rkmsg_r1, machine_const, method_const
rkmsg_r1 calls get_stop_on_fatal_r1, set_saved_state_r1
upstream_calculate calls setup