statistics – ISOFT
statistics Interface
3 statements
Source File
public interface statistics
Calls
Contents
Module Procedures
statistics_r1
Module Procedures
private subroutine statistics_r1(comm, total_f_calls, step_cost, waste, num_succ_steps, h_next, y_maxvals)
Arguments
Type Intent Optional Attributes Name
type(rk_comm_real_1d), intent(inout) :: comm
integer, intent(out), optional :: total_f_calls
integer, intent(out), optional :: step_cost
real(kind=wp), intent(out), optional :: waste
integer, intent(out), optional :: num_succ_steps
real(kind=wp), intent(out), optional :: h_next
real(kind=wp), intent(out), optional dimension(:) :: y_maxvals
Call graph
statistics calls statistics_r1
statistics_r1 calls rkmsg_r1, get_saved_state_r1
rkmsg_r1 calls get_stop_on_fatal_r1, set_saved_state_r1