step_integrate – ISOFT
step_integrate Interface
3 statements
Source File
public interface step_integrate
Calls
Called by
Contents
Module Procedures
step_integrate_r1
Module Procedures
private recursive subroutine step_integrate_r1(comm, f, t_now, y_now, yderiv_now, flag)
Arguments
Type Intent Optional Attributes Name
type(rk_comm_real_1d), intent(inout) :: comm
public function f(t, y)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in), dimension(:) :: y
Return Value real(kind=wp), dimension(size(y,1))
real(kind=wp), intent(out) :: t_now
real(kind=wp), intent(out), dimension(:) :: y_now
real(kind=wp), intent(out), dimension(:) :: yderiv_now
integer, intent(out), optional :: flag
Call graph
step_integrate calls step_integrate_r1
step_integrate_r1 calls truerr_r1, stiff_r1, set_saved_state_r1, step_r1, get_saved_state_r1, rkmsg_r1
truerr_r1 calls step_r1
rkmsg_r1 calls set_saved_state_r1, get_stop_on_fatal_r1
range_integrate_r1 calls step_integrate
range_integrate calls range_integrate_r1
upstream_calculate calls range_integrate